[build]
command = "python manage.py collectstatic --noinput"
command ="source myvenv/scripts/activate"

publish = "./static"  # 정적 파일의 경로


[build.environment]
DJANGO_SETTINGS_MODULE = "h_thon.settings"

site = "ds-savior"
