[build]
command = "python manage.py collectstatic --noinput"
publish = "../static"  # 정적 파일의 경로
exclude = [
    "../myvenv/*",
 ]

[build.environment]
DJANGO_SETTINGS_MODULE = "h_thon.settings"

site = "ds-savior"
